

TICKER_API_URL = 'https://api.coinmarketcap.com/v1/ticker/'
API_KEY = "4xOrAvpSgByUwJ3D16W744eh25p2HbVWS4d4HKU2Ae9h1m28WvFym2csGqcLRoTo"
API_SECRET = "THNXGsYTGP8FHWcoC72pkrbrMytUUmLrmj1EyCtdL1EC5N0j3cWjDEELvtb4dRBs"
CRYPTO_SYMBOLS = ["BTCUSDT", "ETHUSDT", "ETCUSDT", "DOGEUSDT", "BNBUSDT", "SHIBUSDT"]
KLINE_DAYS = 120